language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t abhishek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhishek/react-test npm run test -- --coverage

after_success:
  - docker build -t abhishek/multi-client ./client
  - docker build -t abhishek/multi-nginx ./nginx
  - docker build -t abhishek/multi-server ./server
  - docker build -t abhishek/multi-worker ./worker
  #LOG IN DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push abhishek/multi-client
  - docker push abhishek/multi-nginx
  - docker push abhishek/multi-server
  - docker push abhishek/multi-worker
  